[2025-06-09T11:33:42.849+0200] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: backfill_pollution_weather_dag.format_backfill_all_data manual__2025-06-09T09:33:31.559111+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
