[2025-06-08T21:55:59.041+0200] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: backfill_pollution_weather_dag.format_pollution_backfill manual__2025-06-08T19:55:55.362967+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
