[2025-05-28T20:58:50.303+0200] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: backfill_pollution_weather_dag.format_weather_backfill manual__2025-05-28T18:57:46.429303+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
