[2025-06-09T20:12:44.661+0200] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: fetch_daily_pollution_weather_dag.index_daily_combined_to_elasticsearch scheduled__2025-06-06T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
