[2025-05-29T00:55:17.424+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-29T00:55:17.437+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-29T00:55:17.441+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-29T00:55:17.442+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-29T00:55:17.457+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_daily_data_all_cities> on 2025-05-26 00:00:00+00:00
[2025-05-29T00:55:17.461+0200] {standard_task_runner.py:63} INFO - Started process 394265 to run task
[2025-05-29T00:55:17.463+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_daily_pollution_weather_dag', 'fetch_daily_data_all_cities', 'scheduled__2025-05-26T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpeur7mrji']
[2025-05-29T00:55:17.463+0200] {standard_task_runner.py:91} INFO - Job 53: Subtask fetch_daily_data_all_cities
[2025-05-29T00:55:17.497+0200] {task_command.py:426} INFO - Running <TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-05-29T00:55:17.560+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_daily_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='fetch_daily_data_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T00:00:00+00:00'
[2025-05-29T00:55:17.561+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-29T00:58:00.016+0200] {python.py:237} INFO - Done. Returned value was: None
[2025-05-29T00:58:00.018+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-29T00:58:00.028+0200] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_daily_pollution_weather_dag, task_id=fetch_daily_data_all_cities, execution_date=20250526T000000, start_date=20250528T225517, end_date=20250528T225800
[2025-05-29T00:58:00.145+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-29T00:58:00.242+0200] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-29T00:58:00.305+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-30T17:08:56.537+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-30T17:08:56.548+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-30T17:08:56.552+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-30T17:08:56.552+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-30T17:08:56.568+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_daily_data_all_cities> on 2025-05-26 00:00:00+00:00
[2025-05-30T17:08:56.570+0200] {standard_task_runner.py:63} INFO - Started process 28826 to run task
[2025-05-30T17:08:56.572+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_daily_pollution_weather_dag', 'fetch_daily_data_all_cities', 'scheduled__2025-05-26T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpe5_il25s']
[2025-05-30T17:08:56.572+0200] {standard_task_runner.py:91} INFO - Job 70: Subtask fetch_daily_data_all_cities
[2025-05-30T17:08:56.606+0200] {task_command.py:426} INFO - Running <TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-05-30T17:08:56.659+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_daily_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='fetch_daily_data_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T00:00:00+00:00'
[2025-05-30T17:08:56.660+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-30T17:09:41.278+0200] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-05-30T17:09:41.278+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-30T17:09:41.280+0200] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 28826. PIDs of all processes in the group: [28826]
[2025-05-30T17:09:41.280+0200] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 28826
[2025-05-30T17:09:41.281+0200] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-30T17:09:41.281+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-30T17:09:41.283+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ccd/airflow/dags/daily_dag.py", line 107, in fetch_daily_data
    time.sleep(2)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-30T17:09:41.285+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_daily_pollution_weather_dag, task_id=fetch_daily_data_all_cities, execution_date=20250526T000000, start_date=20250530T150856, end_date=20250530T150941
[2025-05-30T17:09:41.289+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task fetch_daily_data_all_cities ((sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('fetch_daily_data_all_cities', 'fetch_daily_pollution_weather_dag', 'scheduled__2025-05-26T00:00:00+00:00', -1, '2025-05-30 15:08:56.548321', '2025-05-30 15:09:41.285242', 44)]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 28826)
[2025-05-30T17:09:41.294+0200] {process_utils.py:80} INFO - Process psutil.Process(pid=28826, status='terminated', exitcode=1, started='17:08:56') (28826) terminated with exit code 1
[2025-05-30T17:19:13.681+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-30T17:19:13.691+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-30T17:19:13.695+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-30T17:19:13.695+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-30T17:19:13.709+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_daily_data_all_cities> on 2025-05-26 00:00:00+00:00
[2025-05-30T17:19:13.711+0200] {standard_task_runner.py:63} INFO - Started process 31785 to run task
[2025-05-30T17:19:13.714+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_daily_pollution_weather_dag', 'fetch_daily_data_all_cities', 'scheduled__2025-05-26T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmphuqgl853']
[2025-05-30T17:19:13.714+0200] {standard_task_runner.py:91} INFO - Job 79: Subtask fetch_daily_data_all_cities
[2025-05-30T17:19:13.850+0200] {task_command.py:426} INFO - Running <TaskInstance: fetch_daily_pollution_weather_dag.fetch_daily_data_all_cities scheduled__2025-05-26T00:00:00+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-05-30T17:19:13.915+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_daily_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='fetch_daily_data_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T00:00:00+00:00'
[2025-05-30T17:19:13.917+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-30T17:22:08.013+0200] {python.py:237} INFO - Done. Returned value was: None
[2025-05-30T17:22:08.014+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-30T17:22:08.018+0200] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_daily_pollution_weather_dag, task_id=fetch_daily_data_all_cities, execution_date=20250526T000000, start_date=20250530T151913, end_date=20250530T152208
[2025-05-30T17:22:08.050+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-30T17:22:08.057+0200] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-30T17:22:08.066+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
