[2025-05-30T18:03:46.836+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-30T18:03:46.849+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_session manual__2025-05-30T16:03:44.655637+00:00 [queued]>
[2025-05-30T18:03:46.852+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_session manual__2025-05-30T16:03:44.655637+00:00 [queued]>
[2025-05-30T18:03:46.852+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-30T18:03:46.868+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_spark_session> on 2025-05-30 16:03:44.655637+00:00
[2025-05-30T18:03:46.870+0200] {standard_task_runner.py:63} INFO - Started process 44156 to run task
[2025-05-30T18:03:46.874+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'test_spark_connection', 'test_spark_session', 'manual__2025-05-30T16:03:44.655637+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmp3c8bjdas']
[2025-05-30T18:03:46.876+0200] {standard_task_runner.py:91} INFO - Job 87: Subtask test_spark_session
[2025-05-30T18:03:46.908+0200] {task_command.py:426} INFO - Running <TaskInstance: test_spark_connection.test_spark_session manual__2025-05-30T16:03:44.655637+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-05-30T18:03:46.960+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_spark_connection' AIRFLOW_CTX_TASK_ID='test_spark_session' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T16:03:44.655637+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-30T16:03:44.655637+00:00'
[2025-05-30T18:03:46.961+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-30T18:03:47.573+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-30T18:03:47.573+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ccd/airflow/dags/test_spark.py", line 10, in test_spark
    .getOrCreate()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-05-30T18:03:47.578+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_spark_connection, task_id=test_spark_session, execution_date=20250530T160344, start_date=20250530T160346, end_date=20250530T160347
[2025-05-30T18:03:47.592+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task test_spark_session ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 44156)
[2025-05-30T18:03:47.608+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-30T18:03:47.614+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T18:03:47.614+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
